server:
  port: 8080

spring:
  grpc:
    enabled: false

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        # USER
        - id: nonAIService
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
          filters: []

        # AI SERVICE
        - id: ai-service
          uri: http://localhost:8000
          predicates:
            - Path=/api/ai/**
          filters:
            - StripPrefix=1
